In [7]:
import pandas as pd

import numpy as np

import sklearn

from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import MinMaxScaler

In [ ]:
import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

import numpy as np
import sklearn

from sklearn.datasets import load_iris

from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import MinMaxScaler

In [10]:
# housing_price 데이터 실습 해보기
house = pd.read_csv('data/Housing_price.csv')
house.head()
data = house.iloc[:, :5]
data.head()
# 해야할것: 인코딩, 스케일링

      price  area  bedrooms  bathrooms  stories
0  13300000  7420         4          2        3
1  12250000  8960         4          4        4
2  12250000  9960         3          2        2
3  12215000  7500         4          2        2
4  11410000  7420         4          1        2

In [ ]:
# 회귀 데이터에서 price같이 너무 큰 값을 스케일링해서 숫자를 작게 만드는 방법은
# 지금 데이터와 같이 종속변수에서는 사용해선 안된다.
# 즉 예측해야되는 값을 줄여버리면 결과도 줄어버린 값이 나온다.
# invers transform으로 역스케일링할 수 있지만
# 그 과정에서 큰 차이가 발생하여 이상한 값이 되버리는 문제가 발생한다.
# 따라서 종속 변수는 스케일링을 하지 않고 그대로 두고 진행한다.

In [23]:

cat_col = ['bedrooms', 'bathrooms', 'stories']
num_col = ['price', 'area']

# 인코딩
oh_enc = OneHotEncoder(sparse_output = False) # 범주
cat_data = oh_enc.fit_transform(data[cat_col])
cat_df = pd.DataFrame(cat_data, columns = oh_enc.get_feature_names_out())

# 스케일링
mm_scaler = MinMaxScaler()  # 수치
num_data = mm_scaler.fit_transform(data[num_col])
num_df = pd.DataFrame(num_data, columns = mm_scaler.feature_names_in_)

# 합치기
data_df = pd.concat([cat_df, num_df], axis = 1)
data_df.head()

,bedrooms_1,bedrooms_2,bedrooms_3,bedrooms_4,bedrooms_5,bedrooms_6,bathrooms_1,bathrooms_2,bathrooms_3,bathrooms_4,stories_1,stories_2,stories_3,stories_4,price,area
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.000000,0.396564
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.909091,0.502405
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.909091,0.571134
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.906061,0.402062
4,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.836364,0.396564

In [13]:
house = pd.read_csv('data/Housing_price.csv')
data = house.iloc[:, :5]

In [14]:
house.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB

In [15]:
house.dtypes[house.dtypes == 'str']

mainroad            str
guestroom           str
basement            str
hotwaterheating     str
airconditioning     str
prefarea            str
furnishingstatus    str
dtype: object

In [16]:
house.dtypes[house.dtypes == 'str'].index

Index(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [ ]:

cat_col = house.dtypes[house.dtypes == 'str'].index
num_col = house.dtypes[house.dtypes != 'str'].index

In [25]:
# 독립변수와 종속변수를 분리

X = house.drop('price', axis = 1)
y = house['price']

# 변수형과 수치형 독립변수를 분리
cat_col = X.dtypes[house.dtypes == 'str'].index
num_col = X.dtypes[house.dtypes != 'str'].index

# 인코딩
oh_enc = OneHotEncoder(sparse_output = False) # 범주
cat_data = oh_enc.fit_transform(X[cat_col])

# 스케일링
mm_scaler = MinMaxScaler()  # 수치
num_data = mm_scaler.fit_transform(X[num_col])
data_arr = np.concatenate([cat_data, num_data], axis = 1)
data_arr

array([[0.        , 1.        , 1.        , ..., 0.33333333, 0.66666667,
        0.66666667],
       [0.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 1.        , 1.        , ..., 0.33333333, 0.33333333,
        0.66666667],
       ...,
       [0.        , 1.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 1.        , ..., 0.        , 0.33333333,
        0.        ]], shape=(545, 20))

In [29]:
# one-hot
X_dummies = pd.get_dummies(X)
X_dummies.head()

,area,bedrooms,bathrooms,stories,parking,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,basement_no,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,7420,4,2,3,2,False,True,True,False,True,False,True,False,False,True,False,True,True,False,False
1,8960,4,4,4,3,False,True,True,False,True,False,True,False,False,True,True,False,True,False,False
2,9960,3,2,2,2,False,True,True,False,False,True,True,False,True,False,False,True,False,True,False
3,7500,4,2,2,3,False,True,True,False,False,True,True,False,False,True,False,True,True,False,False
4,7420,4,1,2,2,False,True,False,True,False,True,True,False,False,True,True,False,True,False,False

In [ ]:
# MinMax
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_dummies)
X_scaled

array([[0.39656357, 0.6       , 0.33333333, ..., 1.        , 0.        ,
        0.        ],
       [0.5024055 , 0.6       , 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.57113402, 0.4       , 0.33333333, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.13539519, 0.2       , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.08659794, 0.4       , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.15120275, 0.4       , 0.        , ..., 0.        , 0.        ,
        1.        ]], shape=(545, 20))

In [31]:
oh_enc = OneHotEncoder()
cat_data = oh_enc.fit_transform(X[cat_col])
print(cat_data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3815 stored elements and shape (545, 15)>
  Coords	Values
  (0, 1)	1.0
  (0, 2)	1.0
  (0, 4)	1.0
  (0, 6)	1.0
  (0, 9)	1.0
  (0, 11)	1.0
  (0, 12)	1.0
  (1, 1)	1.0
  (1, 2)	1.0
  (1, 4)	1.0
  (1, 6)	1.0
  (1, 9)	1.0
  (1, 10)	1.0
  (1, 12)	1.0
  (2, 1)	1.0
  (2, 2)	1.0
  (2, 5)	1.0
  (2, 6)	1.0
  (2, 8)	1.0
  (2, 11)	1.0
  (2, 13)	1.0
  (3, 1)	1.0
  (3, 2)	1.0
  (3, 5)	1.0
  (3, 6)	1.0
  :	:
  (541, 6)	1.0
  (541, 8)	1.0
  (541, 10)	1.0
  (541, 13)	1.0
  (542, 1)	1.0
  (542, 2)	1.0
  (542, 4)	1.0
  (542, 6)	1.0
  (542, 8)	1.0
  (542, 10)	1.0
  (542, 14)	1.0
  (543, 0)	1.0
  (543, 2)	1.0
  (543, 4)	1.0
  (543, 6)	1.0
  (543, 8)	1.0
  (543, 10)	1.0
  (543, 12)	1.0
  (544, 1)	1.0
  (544, 2)	1.0
  (544, 4)	1.0
  (544, 6)	1.0
  (544, 8)	1.0
  (544, 10)	1.0
  (544, 14)	1.0