In [ ]:
# NLP모델이다 -> 아 텍스트를 다루는 모델이구나 라고 생각하면 됨

- 텍스트 전처리
  1. 클렌징: 텍스트에서 불필요한 문자, 기호 등을 사전에 제거한다.

In [2]:
with open('./data/stevejobs.txt', 'r', encoding='utf8') as f:
    rows = f.readlines()
    lines = [row for row in rows]
text = ' '.join(lines)
print(text[:200])

This is the text of the Commencement address by Steve Jobs, CEO of Apple Computer and of Pixar Animation Studios, delivered on June 12, 2005.


 I am honored to be with you today at your commenceme

In [3]:
import re

compile = re.compile("[^ a-zA-Z0-9\\.]+")
text = compile.sub('',text).lower()
print(text[:200])

this is the text of the commencement address by steve jobs ceo of apple computer and of pixar animation studios delivered on june 12 2005.    i am honored to be with you today at your commencement fro

2. 텍스트 토큰화: 문장을 분리하고, 단어를 분리하여 토큰으로 만드는 작업

In [10]:
# 문장 토큰화
# 토큰화(tokenize): 텍스트를 의미있는 조각(토큰)으로 쪼개는 작업
import nltk
    # - nlkt: 영어 텍스트 처리용 대표 라이브러리(Natural Language Toolkit)

nltk.download('punkt_tab')
    # - punk_tab: 문장 경계를 판단하는 학습된 모델
    # - 라이브러리 본체와 별개로, 작업에 필요한 것들을 download()로 따로 받아야함
    # - 얘를 다운받아야 문장이나 단어를 분리하고 토큰화 할 수 있음
    # - 마침표가 문장 끝인지, Mr./ U.S. 같은 약어인지 구분해줌

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\samsung1\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [14]:
sentences = nltk.sent_tokenize(text = text)
    # - sent_tokenize: 긴 글 하나를 문장 단위로 잘라 리스트로 만듬
    #   (punkt_tab을 다운받아야 sent_tokenize명령어를 쓸 수 있음)
    # - word_tokenize: 단어 단위로 쪼갬
    # - ★ 앞 셀에서 정규식으로 클렌징할 때 마침표(\.)를 일부러 남긴 이유가 이것

print(sentences[:3])
    # - 앞 3문장만 확인(전체로 찍으면 너무 김)

['this is the text of the commencement address by steve jobs ceo of apple computer and of pixar animation studios delivered on june 12 2005.    i am honored to be with you today at your commencement from one of the finest universities in the world.', 'i never graduated from college.', 'truth be told this is the closest ive ever gotten to a college graduation.']

In [15]:
# sent_tokenize 결과 간단 예시
example_sentences = nltk.sent_tokenize(text = 'im hungry. i want to eat')

print(example_sentences)

    # 결과를 보면 마침표 기준으로 문장이 나눠진 것을 확인 할 수 있음

['im hungry.', 'i want to eat']

In [12]:
# 단어 토큰화
word_token = []
for sentence in sentences:
    words = nltk.word_tokenize(sentence)
    word_token.extend(words)
print(word_token[:10])

['this', 'is', 'the', 'text', 'of', 'the', 'commencement', 'address', 'by', 'steve']

In [16]:
nltk.word_tokenize(text = 'imhungrydoyou')
    # 띄어쓰기 안하면 안나눠짐

['imhungrydoyou']

In [17]:
nltk.word_tokenize(text = '나는 배가 고프다')

# 한글은 nltk잘 안쓴다고 하는데

['나는', '배가', '고프다']

3. 스톱워드 제거: 분석에 큰 의미 없는 단어 제거(this, is 등)

In [19]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\samsung1\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [20]:
stopwords = nltk.corpus.stopwords.words('english')
print('영어 stop words 개수: ',len(stopwords))
print(stopwords[:10])

영어 stop words 개수:  198
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an']

In [ ]:
filtered_words = []
for word in word_token:
    if word not in stopwords:
        filtered_words.append(word)
print(filtered_words[:10])

['text', 'commencement', 'address', 'steve', 'jobs', 'ceo', 'apple', 'computer', 'pixar', 'animation']

- Stemming과 Lemmatization: 단어의 원형을 찾는 기법

In [23]:
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('working'))
print(stemmer.stem('works'))
print(stemmer.stem('worked'))

work
work
work

In [26]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\samsung1\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [25]:
lemma = WordNetLemmatizer()

print(lemma.lemmatize('amusing','v'))
print(lemma.lemmatize('amuses','v'))
print(lemma.lemmatize('amused','v'))

amuse
amuse
amuse

In [27]:
print(stemmer.stem('happier'), stemmer.stem('happiest'))
print(lemma.lemmatize('happier','a'))
print(lemma.lemmatize('happiest','a'))

happy happiest
happy
happy

In [ ]:
filtered_words = []
for word in word_token:
    stemmed_word = stemmer.stem(word)
    if stemmed_word not in stopwords:
        filtered_words.append(stemmed_word)
print(filtered_words[:10])

# stemmed를 사용하면 this -> thi, pixar -> pix, apple -> appl로 이상하게 잘린다.
# 이상하게 잘리기 때문에 요즘에는 stemming은 잘 사용하지 않는다.

['thi', 'text', 'com', 'address', 'stev', 'job', 'ceo', 'appl', 'comput', 'pix']

In [36]:
from sklearn.feature_extraction.text import CountVectorizer

In [37]:
sentences = ["I like machine learning and data science", 
             "Machine learning is useful for data analysis", 
             "Python is popular for machine learning", 
             "I like Python and data analysis", 
             "Data science uses Python and machine learning" 
             ]

In [39]:
cnt_vect = CountVectorizer()
cnt_vect.fit(sentences)
sent = cnt_vect.transform(sentences)

In [40]:
sent

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 31 stored elements and shape (5, 13)>

In [41]:
cnt_vect.vocabulary_

{'like': 6,
 'machine': 7,
 'learning': 5,
 'and': 1,
 'data': 2,
 'science': 10,
 'is': 4,
 'useful': 11,
 'for': 3,
 'analysis': 0,
 'python': 9,
 'popular': 8,
 'uses': 12}

In [42]:
cnt_vect.get_feature_names_out()

array(['analysis', 'and', 'data', 'for', 'is', 'learning', 'like',
       'machine', 'popular', 'python', 'science', 'useful', 'uses'],
      dtype=object)

In [43]:
import pandas as pd

pd.DataFrame(sent.toarray(), columns = cnt_vect.get_feature_names_out())

,analysis,and,data,for,is,learning,like,machine,popular,python,science,useful,uses
0,0,1,1,0,0,1,1,1,0,0,1,0,0
1,1,0,1,1,1,1,0,1,0,0,0,1,0
2,0,0,0,1,1,1,0,1,1,1,0,0,0
3,1,1,1,0,0,0,1,0,0,1,0,0,0
4,0,1,1,0,0,1,0,1,0,1,1,0,1

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf.fit(sentences)
sent_tf = tfidf.transform(sentences)

In [46]:
pd.DataFrame(sent_tf.toarray(), columns = tfidf.get_feature_names_out())

,analysis,and,data,for,is,learning,like,machine,popular,python,science,useful,uses
0,0.000000,0.407382,0.342702,0.000000,0.000000,0.342702,0.490768,0.342702,0.000000,0.000000,0.490768,0.000000,0.000000
1,0.408277,0.000000,0.285099,0.408277,0.408277,0.285099,0.000000,0.285099,0.000000,0.000000,0.000000,0.506049,0.000000
2,0.000000,0.000000,0.000000,0.438504,0.438504,0.306207,0.000000,0.306207,0.543515,0.363998,0.000000,0.000000,0.000000
3,0.508610,0.422192,0.355161,0.000000,0.000000,0.000000,0.508610,0.000000,0.000000,0.422192,0.000000,0.000000,0.000000
4,0.000000,0.357969,0.301134,0.000000,0.000000,0.301134,0.000000,0.301134,0.000000,0.357969,0.431241,0.000000,0.534512

In [50]:
stopwords = nltk.corpus.stopwords.words('english')

cnt_vect = CountVectorizer(stop_words=stopwords)
cnt_vect.fit(sentences)
sent = cnt_vect.transform(sentences)

cnt_vect.get_feature_names_out()

array(['analysis', 'data', 'learning', 'like', 'machine', 'popular',
       'python', 'science', 'useful', 'uses'], dtype=object)

In [51]:
stopwords = nltk.corpus.stopwords.words('english')

cnt_vect = CountVectorizer(stop_words=stopwords, tokenizer=nltk.word_tokenize)
cnt_vect.fit(sentences)
sent = cnt_vect.transform(sentences)
cnt_vect.get_feature_names_out()

c:\Users\samsung1\git_project\samsung_practice\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:527: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\samsung1\git_project\samsung_practice\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:412: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ["'d", "'ll", "'m", "'re", "'s", "'ve", 'could', 'might', 'must', "n't", 'need', 'sha', 'wo', 'would'] not in stop_words.
  warnings.warn(

array(['analysis', 'data', 'learning', 'like', 'machine', 'popular',
       'python', 'science', 'useful', 'uses'], dtype=object)

In [58]:
sentences = ["I like machine learning and data science", 
             "Machine learning is useful for data analysis", 
             "Python is popular for machine learning", 
             "I like Python and data analysis", 
             "Data science uses Python and machine learning" 
             ]

cnt_vect = CountVectorizer(max_df=0.7)
cnt_vect.fit(sentences)
cnt_vect.get_feature_names_out()

# 결과를 보면 machine도 없고 learning도 없고 data도 없는 것을 확인 할 수 있다.
#

array(['analysis', 'and', 'for', 'is', 'like', 'popular', 'python',
       'science', 'useful', 'uses'], dtype=object)

In [59]:
cnt_vect = CountVectorizer(max_df=0.8)
cnt_vect.fit(sentences)
cnt_vect.get_feature_names_out()

# 80%까지 올리면 machine, learning, data가 살아남는다.

array(['analysis', 'and', 'data', 'for', 'is', 'learning', 'like',
       'machine', 'popular', 'python', 'science', 'useful', 'uses'],
      dtype=object)

In [60]:
cnt_vect = CountVectorizer(max_df=3)
cnt_vect.fit(sentences)
cnt_vect.get_feature_names_out()

# 3개가 마지노선이라는 뜻. 4개이상인 단어들은 다 지워짐
# 즉 횟수를 지정할 수 도 있고, 비율을 지정할 수도 이싿.

array(['analysis', 'and', 'for', 'is', 'like', 'popular', 'python',
       'science', 'useful', 'uses'], dtype=object)

In [61]:
cnt_vect = CountVectorizer(max_df=2)
cnt_vect.fit(sentences)
cnt_vect.get_feature_names_out()

# 결과에 나온 단어들은 모두 한번밖에 안나왔다는 의미

array(['analysis', 'for', 'is', 'like', 'popular', 'science', 'useful',
       'uses'], dtype=object)

In [ ]:
cnt_vect = CountVectorizer(max_features= 10)
cnt_vect.fit(sentences)
cnt_vect.get_feature_names_out()

#

array(['analysis', 'and', 'data', 'for', 'is', 'learning', 'like',
       'machine', 'python', 'science'], dtype=object)

In [ ]:
cnt_vect = CountVectorizer(ngram_range=(1, 2))
    # 

cnt_vect.fit(sentences)
cnt_vect.get_feature_names_out()

#

array(['analysis', 'and', 'and data', 'and machine', 'data',
       'data analysis', 'data science', 'for', 'for data', 'for machine',
       'is', 'is popular', 'is useful', 'learning', 'learning and',
       'learning is', 'like', 'like machine', 'like python', 'machine',
       'machine learning', 'popular', 'popular for', 'python',
       'python and', 'python is', 'science', 'science uses', 'useful',
       'useful for', 'uses', 'uses python'], dtype=object)

- 텍스트 분류 실습 - 20 뉴스 그룹

In [ ]:
from sklearn.datasets import fetch_20newsgroups
import pandas as pd

news_data = fetch_20newsgroups(subset = 'all', random_state = 156)
print(news_data.data[0])

From: egreen@east.sun.com (Ed Green - Pixel Cruncher)
Subject: Re: Observation re: helmets
Organization: Sun Microsystems, RTP, NC
Lines: 21
Distribution: world
Reply-To: egreen@east.sun.com
NNTP-Posting-Host: laser.east.sun.com

In article 211353@mavenry.altcit.eskimo.com, maven@mavenry.altcit.eskimo.com (Norman Hamer) writes:
>
> The question for the day is re: passenger helmets, if you don't know for
>certain who's gonna ride with you (like say you meet them at a .... church
>meeting, yeah, that's the ticket)... What are some guidelines? Should I just
>pick up another shoei in my size to have a backup helmet (XL), or should I
>maybe get an inexpensive one of a smaller size to accomodate my likely
>passenger?

If your primary concern is protecting the passenger in the event of a
crash, have him or her fitted for a helmet that is their size.  If your
primary concern is complying with stupid helmet laws, carry a real big
spare (you can put a big or small head in a big helmet, but not in a
small one).

---
Ed Green, former Ninjaite |I was drinking last night with a biker,
  Ed.Green@East.Sun.COM   |and I showed him a picture of you.  I said,
DoD #0111  (919)460-8302  |"Go on, get to know her, you'll like her!"
 (The Grateful Dead) -->  |It seemed like the least I could do...

In [ ]:
news_data.target_names

# 이 문장이 어떤 카테고리에 속해있냐 이거ㅣㅇㅁ

# comp는 computer를 의미
# comp.graphics는 컴퓨터에서 그래픽 관련 내용 뭐 이런식

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [ ]:
train_news= fetch_20newsgroups(subset='train', 
                               remove=('headers', 'footers', 'quotes'), 
                               random_state=156
                               )
X_train = train_news.data
y_train = train_news.target
print(X_train[0])

# 이 결과가 하나의 텍스트 데이터(문서)

What I did NOT get with my drive (CD300i) is the System Install CD you
listed as #1.  Any ideas about how I can get one?  I bought my IIvx 8/120
from Direct Express in Chicago (no complaints at all -- good price & good
service).

BTW, I've heard that the System Install CD can be used to boot the mac;
however, my drive will NOT accept a CD caddy is the machine is off.  How can
you boot with it then?

--Dave

In [66]:
test_news= fetch_20newsgroups(subset='test', 
                              remove=('headers', 'footers','quotes'), 
                              random_state=156
                              )
X_test = test_news.data
y_test = test_news.target
print(f'학습 데이터 크기 {len(train_news.data)}, 테스트 데이터 크기 {len(test_news.data)}')

학습 데이터 크기 11314, 테스트 데이터 크기 7532

In [67]:
from sklearn.feature_extraction.text import CountVectorizer

cnt_vect = CountVectorizer()
cnt_vect.fit(X_train)
X_train_cnt_vect = cnt_vect.transform(X_train)
X_test_cnt_vect = cnt_vect.transform(X_test)

print('학습 데이터 Text의 CountVectorizer Shape:', X_train_cnt_vect.shape)

학습 데이터 Text의 CountVectorizer Shape: (11314, 101631)

In [69]:
from sklearn.feature_extraction.text import CountVectorizer

cnt_vect = CountVectorizer()
cnt_vect.fit(X_train)
X_train_cnt_vect = cnt_vect.transform(X_train)
X_test_cnt_vect = cnt_vect.transform(X_test)

print('학습 데이터 Text의 CountVectorizer Shape:', X_train_cnt_vect.shape)

학습 데이터 Text의 CountVectorizer Shape: (11314, 101631)

In [72]:
X_train_cnt_vect

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1103627 stored elements and shape (11314, 101631)>

In [71]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

lr_clf = LogisticRegression()
lr_clf.fit(X_train_cnt_vect , y_train)
pred = lr_clf.predict(X_test_cnt_vect)
print('예측 정확도는 {0:.3f}'.format(accuracy_score(y_test, pred)))

예측 정확도는 0.608

In [ ]:
y_test[0]

# 결과
# np.int64(4)
# 
# 4번 카테고리에 있는 'comp.sys.mac.hardware' 관련 내용이라는 뜻

np.int64(4)

In [77]:
print(X_test[0])

The tech support line for GCC is 1-800-231-1570.

In [ ]:
cnt_vect = CountVectorizer(min_df=10, max_df=0.85, stop_words='english')
cnt_vect.fit(X_train)
X_train_cnt_vect = cnt_vect.transform(X_train)
X_test_cnt_vect = cnt_vect.transform(X_test)

print('학습 데이터 Text의 CountVectorizer Shape:', X_train_cnt_vect.shape)

# 단어 10만개가 1만개로 줄어든것을 확인 할 수 있음

학습 데이터 Text의 CountVectorizer Shape: (11314, 10441)

In [73]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer()
tfidf_vect.fit(X_train)
X_train_tfidf_vect = tfidf_vect.transform(X_train)
X_test_tfidf_vect = tfidf_vect.transform(X_test)
lr_clf = LogisticRegression()
lr_clf.fit(X_train_tfidf_vect , y_train)
pred = lr_clf.predict(X_test_tfidf_vect)
print('예측 정확도는 {0:.3f}'.format(accuracy_score(y_test ,pred)))

예측 정확도는 0.674

In [ ]:
lr_clf = LogisticRegression()
lr_clf.fit(X_train_cnt_vect , y_train)
pred = lr_clf.predict(X_test_cnt_vect)
print('예측 정확도는 {0:.3f}'.format(accuracy_score(y_test, pred)))

# 0.608에서 0.613으로 정확도가 조금 더 증가한 것을 확인 할 수 있다.

예측 정확도는 0.613

In [80]:
cnt_vect = CountVectorizer(min_df=10, max_df=0.85, stop_words='english', ngram_range=(1, 2))
# ngram_range=(1, 2)추가

cnt_vect.fit(X_train)
X_train_cnt_vect = cnt_vect.transform(X_train)
X_test_cnt_vect = cnt_vect.transform(X_test)

print('학습 데이터 Text의 CountVectorizer Shape:', X_train_cnt_vect.shape)

학습 데이터 Text의 CountVectorizer Shape: (11314, 12721)

In [ ]:
tfidf_vect = TfidfVectorizer(min_df=10, max_df=0.85, stop_words='english', ngram_range=(1, 2))

tfidf_vect.fit(X_train)
X_train_cnt_vect = tfidf_vect.transform(X_train)
X_test_cnt_vect = tfidf_vect.transform(X_test)

print('학습 데이터 Text의 CountVectorizer Shape:', X_train_tfidf_vect.shape)