In [ ]:
# NLP모델이다 -> 아 텍스트를 다루는 모델이구나 라고 생각하면 됨

- 텍스트 전처리
  1. 클렌징: 텍스트에서 불필요한 문자, 기호 등을 사전에 제거한다.

In [2]:
with open('./data/stevejobs.txt', 'r', encoding='utf8') as f:
    rows = f.readlines()
    lines = [row for row in rows]
text = ' '.join(lines)
print(text[:200])

This is the text of the Commencement address by Steve Jobs, CEO of Apple Computer and of Pixar Animation Studios, delivered on June 12, 2005.


 I am honored to be with you today at your commenceme

In [3]:
import re

compile = re.compile("[^ a-zA-Z0-9\\.]+")
text = compile.sub('',text).lower()
print(text[:200])

this is the text of the commencement address by steve jobs ceo of apple computer and of pixar animation studios delivered on june 12 2005.    i am honored to be with you today at your commencement fro

2. 텍스트 토큰화: 문장을 분리하고, 단어를 분리하여 토큰으로 만드는 작업

In [10]:
# 문장 토큰화
# 토큰화(tokenize): 텍스트를 의미있는 조각(토큰)으로 쪼개는 작업
import nltk
    # - nlkt: 영어 텍스트 처리용 대표 라이브러리(Natural Language Toolkit)

nltk.download('punkt_tab')
    # - punk_tab: 문장 경계를 판단하는 학습된 모델
    # - 라이브러리 본체와 별개로, 작업에 필요한 것들을 download()로 따로 받아야함
    # - 얘를 다운받아야 문장이나 단어를 분리하고 토큰화 할 수 있음
    # - 마침표가 문장 끝인지, Mr./ U.S. 같은 약어인지 구분해줌

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\samsung1\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [14]:
sentences = nltk.sent_tokenize(text = text)
    # - sent_tokenize: 긴 글 하나를 문장 단위로 잘라 리스트로 만듬
    #   (punkt_tab을 다운받아야 sent_tokenize명령어를 쓸 수 있음)
    # - word_tokenize: 단어 단위로 쪼갬
    # - ★ 앞 셀에서 정규식으로 클렌징할 때 마침표(\.)를 일부러 남긴 이유가 이것

print(sentences[:3])
    # - 앞 3문장만 확인(전체로 찍으면 너무 김)

['this is the text of the commencement address by steve jobs ceo of apple computer and of pixar animation studios delivered on june 12 2005.    i am honored to be with you today at your commencement from one of the finest universities in the world.', 'i never graduated from college.', 'truth be told this is the closest ive ever gotten to a college graduation.']

In [15]:
# sent_tokenize 결과 간단 예시
example_sentences = nltk.sent_tokenize(text = 'im hungry. i want to eat')

print(example_sentences)

    # 결과를 보면 마침표 기준으로 문장이 나눠진 것을 확인 할 수 있음

['im hungry.', 'i want to eat']

In [12]:
# 단어 토큰화
word_token = []
for sentence in sentences:
    words = nltk.word_tokenize(sentence)
    word_token.extend(words)
print(word_token[:10])

['this', 'is', 'the', 'text', 'of', 'the', 'commencement', 'address', 'by', 'steve']

In [16]:
nltk.word_tokenize(text = 'imhungrydoyou')
    # 띄어쓰기 안하면 안나눠짐

['imhungrydoyou']

In [17]:
nltk.word_tokenize(text = '나는 배가 고프다')

# 한글은 nltk잘 안쓴다고 하는데

['나는', '배가', '고프다']

3. 스톱워드 제거: 분석에 큰 의미 없는 단어 제거(this, is 등)

In [19]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\samsung1\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [20]:
stopwords = nltk.corpus.stopwords.words('english')
print('영어 stop words 개수: ',len(stopwords))
print(stopwords[:10])

영어 stop words 개수:  198
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an']

In [ ]:
filtered_words = []
for word in word_token:
    if word not in stopwords:
        filtered_words.append(word)
print(filtered_words[:10])

['text', 'commencement', 'address', 'steve', 'jobs', 'ceo', 'apple', 'computer', 'pixar', 'animation']

- Stemming과 Lemmatization: 단어의 원형을 찾는 기법

In [23]:
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('working'))
print(stemmer.stem('works'))
print(stemmer.stem('worked'))

work
work
work

In [26]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\samsung1\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [25]:
lemma = WordNetLemmatizer()

print(lemma.lemmatize('amusing','v'))
print(lemma.lemmatize('amuses','v'))
print(lemma.lemmatize('amused','v'))

amuse
amuse
amuse

In [27]:
print(stemmer.stem('happier'), stemmer.stem('happiest'))
print(lemma.lemmatize('happier','a'))
print(lemma.lemmatize('happiest','a'))

happy happiest
happy
happy

In [ ]:
filtered_words = []
for word in word_token:
    stemmed_word = stemmer.stem(word)
    if stemmed_word not in stopwords:
        filtered_words.append(stemmed_word)
print(filtered_words[:10])

# stemmed를 사용하면 this -> thi, pixar -> pix, apple -> appl로 이상하게 잘린다.
# 이상하게 잘리기 때문에 요즘에는 stemming은 잘 사용하지 않는다.

['thi', 'text', 'com', 'address', 'stev', 'job', 'ceo', 'appl', 'comput', 'pix']

In [36]:
from sklearn.feature_extraction.text import CountVectorizer

In [37]:
sentences = ["I like machine learning and data science", 
             "Machine learning is useful for data analysis", 
             "Python is popular for machine learning", 
             "I like Python and data analysis", 
             "Data science uses Python and machine learning" 
             ]

In [39]:
cnt_vect = CountVectorizer()
cnt_vect.fit(sentences)
sent = cnt_vect.transform(sentences)

In [40]:
sent

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 31 stored elements and shape (5, 13)>

In [41]:
cnt_vect.vocabulary_

{'like': 6,
 'machine': 7,
 'learning': 5,
 'and': 1,
 'data': 2,
 'science': 10,
 'is': 4,
 'useful': 11,
 'for': 3,
 'analysis': 0,
 'python': 9,
 'popular': 8,
 'uses': 12}

In [42]:
cnt_vect.get_feature_names_out()

array(['analysis', 'and', 'data', 'for', 'is', 'learning', 'like',
       'machine', 'popular', 'python', 'science', 'useful', 'uses'],
      dtype=object)

In [43]:
import pandas as pd

pd.DataFrame(sent.toarray(), columns = cnt_vect.get_feature_names_out())

,analysis,and,data,for,is,learning,like,machine,popular,python,science,useful,uses
0,0,1,1,0,0,1,1,1,0,0,1,0,0
1,1,0,1,1,1,1,0,1,0,0,0,1,0
2,0,0,0,1,1,1,0,1,1,1,0,0,0
3,1,1,1,0,0,0,1,0,0,1,0,0,0
4,0,1,1,0,0,1,0,1,0,1,1,0,1

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf.fit(sentences)
sent_tf = tfidf.transform(sentences)

In [46]:
pd.DataFrame(sent_tf.toarray(), columns = tfidf.get_feature_names_out())

,analysis,and,data,for,is,learning,like,machine,popular,python,science,useful,uses
0,0.000000,0.407382,0.342702,0.000000,0.000000,0.342702,0.490768,0.342702,0.000000,0.000000,0.490768,0.000000,0.000000
1,0.408277,0.000000,0.285099,0.408277,0.408277,0.285099,0.000000,0.285099,0.000000,0.000000,0.000000,0.506049,0.000000
2,0.000000,0.000000,0.000000,0.438504,0.438504,0.306207,0.000000,0.306207,0.543515,0.363998,0.000000,0.000000,0.000000
3,0.508610,0.422192,0.355161,0.000000,0.000000,0.000000,0.508610,0.000000,0.000000,0.422192,0.000000,0.000000,0.000000
4,0.000000,0.357969,0.301134,0.000000,0.000000,0.301134,0.000000,0.301134,0.000000,0.357969,0.431241,0.000000,0.534512

In [50]:
stopwords = nltk.corpus.stopwords.words('english')

cnt_vect = CountVectorizer(stop_words=stopwords)
cnt_vect.fit(sentences)
sent = cnt_vect.transform(sentences)

cnt_vect.get_feature_names_out()

array(['analysis', 'data', 'learning', 'like', 'machine', 'popular',
       'python', 'science', 'useful', 'uses'], dtype=object)

In [51]:
stopwords = nltk.corpus.stopwords.words('english')

cnt_vect = CountVectorizer(stop_words=stopwords, tokenizer=nltk.word_tokenize)
cnt_vect.fit(sentences)
sent = cnt_vect.transform(sentences)
cnt_vect.get_feature_names_out()

c:\Users\samsung1\git_project\samsung_practice\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:527: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\samsung1\git_project\samsung_practice\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:412: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ["'d", "'ll", "'m", "'re", "'s", "'ve", 'could', 'might', 'must', "n't", 'need', 'sha', 'wo', 'would'] not in stop_words.
  warnings.warn(

array(['analysis', 'data', 'learning', 'like', 'machine', 'popular',
       'python', 'science', 'useful', 'uses'], dtype=object)

In [58]:
sentences = ["I like machine learning and data science", 
             "Machine learning is useful for data analysis", 
             "Python is popular for machine learning", 
             "I like Python and data analysis", 
             "Data science uses Python and machine learning" 
             ]

cnt_vect = CountVectorizer(max_df=0.7)
cnt_vect.fit(sentences)
cnt_vect.get_feature_names_out()

# 결과를 보면 machine도 없고 learning도 없고 data도 없는 것을 확인 할 수 있다.
#

array(['analysis', 'and', 'for', 'is', 'like', 'popular', 'python',
       'science', 'useful', 'uses'], dtype=object)

In [59]:
cnt_vect = CountVectorizer(max_df=0.8)
cnt_vect.fit(sentences)
cnt_vect.get_feature_names_out()

# 80%까지 올리면 machine, learning, data가 살아남는다.

array(['analysis', 'and', 'data', 'for', 'is', 'learning', 'like',
       'machine', 'popular', 'python', 'science', 'useful', 'uses'],
      dtype=object)

In [60]:
cnt_vect = CountVectorizer(max_df=3)
cnt_vect.fit(sentences)
cnt_vect.get_feature_names_out()

# 3개가 마지노선이라는 뜻. 4개이상인 단어들은 다 지워짐
# 즉 횟수를 지정할 수 도 있고, 비율을 지정할 수도 이싿.

array(['analysis', 'and', 'for', 'is', 'like', 'popular', 'python',
       'science', 'useful', 'uses'], dtype=object)

In [61]:
cnt_vect = CountVectorizer(max_df=2)
cnt_vect.fit(sentences)
cnt_vect.get_feature_names_out()

# 결과에 나온 단어들은 모두 한번밖에 안나왔다는 의미

array(['analysis', 'for', 'is', 'like', 'popular', 'science', 'useful',
       'uses'], dtype=object)

In [ ]:
cnt_vect = CountVectorizer(max_features= 10)
cnt_vect.fit(sentences)
cnt_vect.get_feature_names_out()

#

array(['analysis', 'and', 'data', 'for', 'is', 'learning', 'like',
       'machine', 'python', 'science'], dtype=object)

In [ ]:
cnt_vect = CountVectorizer(ngram_range=(1, 2))
    # 

cnt_vect.fit(sentences)
cnt_vect.get_feature_names_out()

#

array(['analysis', 'and', 'and data', 'and machine', 'data',
       'data analysis', 'data science', 'for', 'for data', 'for machine',
       'is', 'is popular', 'is useful', 'learning', 'learning and',
       'learning is', 'like', 'like machine', 'like python', 'machine',
       'machine learning', 'popular', 'popular for', 'python',
       'python and', 'python is', 'science', 'science uses', 'useful',
       'useful for', 'uses', 'uses python'], dtype=object)

- 텍스트 분류 실습 - 20 뉴스 그룹

In [ ]:
from sklearn.datasets import fetch_20newsgroups
import pandas as pd

news_data = fetch_20newsgroups(subset = 'all', random_state = 156)
print(news_data.data[0])

From: egreen@east.sun.com (Ed Green - Pixel Cruncher)
Subject: Re: Observation re: helmets
Organization: Sun Microsystems, RTP, NC
Lines: 21
Distribution: world
Reply-To: egreen@east.sun.com
NNTP-Posting-Host: laser.east.sun.com

In article 211353@mavenry.altcit.eskimo.com, maven@mavenry.altcit.eskimo.com (Norman Hamer) writes:
>
> The question for the day is re: passenger helmets, if you don't know for
>certain who's gonna ride with you (like say you meet them at a .... church
>meeting, yeah, that's the ticket)... What are some guidelines? Should I just
>pick up another shoei in my size to have a backup helmet (XL), or should I
>maybe get an inexpensive one of a smaller size to accomodate my likely
>passenger?

If your primary concern is protecting the passenger in the event of a
crash, have him or her fitted for a helmet that is their size.  If your
primary concern is complying with stupid helmet laws, carry a real big
spare (you can put a big or small head in a big helmet, but not in a
small one).

---
Ed Green, former Ninjaite |I was drinking last night with a biker,
  Ed.Green@East.Sun.COM   |and I showed him a picture of you.  I said,
DoD #0111  (919)460-8302  |"Go on, get to know her, you'll like her!"
 (The Grateful Dead) -->  |It seemed like the least I could do...

In [ ]:
news_data.target_names

# 이 문장이 어떤 카테고리에 속해있냐 이거ㅣㅇㅁ

# comp는 computer를 의미
# comp.graphics는 컴퓨터에서 그래픽 관련 내용 뭐 이런식

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [ ]:
train_news= fetch_20newsgroups(subset='train', 
                               remove=('headers', 'footers', 'quotes'), 
                               random_state=156
                               )
X_train = train_news.data
y_train = train_news.target
print(X_train[0])

# 이 결과가 하나의 텍스트 데이터(문서)

What I did NOT get with my drive (CD300i) is the System Install CD you
listed as #1.  Any ideas about how I can get one?  I bought my IIvx 8/120
from Direct Express in Chicago (no complaints at all -- good price & good
service).

BTW, I've heard that the System Install CD can be used to boot the mac;
however, my drive will NOT accept a CD caddy is the machine is off.  How can
you boot with it then?

--Dave

In [66]:
test_news= fetch_20newsgroups(subset='test', 
                              remove=('headers', 'footers','quotes'), 
                              random_state=156
                              )
X_test = test_news.data
y_test = test_news.target
print(f'학습 데이터 크기 {len(train_news.data)}, 테스트 데이터 크기 {len(test_news.data)}')

학습 데이터 크기 11314, 테스트 데이터 크기 7532

In [67]:
from sklearn.feature_extraction.text import CountVectorizer

cnt_vect = CountVectorizer()
cnt_vect.fit(X_train)
X_train_cnt_vect = cnt_vect.transform(X_train)
X_test_cnt_vect = cnt_vect.transform(X_test)

print('학습 데이터 Text의 CountVectorizer Shape:', X_train_cnt_vect.shape)

학습 데이터 Text의 CountVectorizer Shape: (11314, 101631)

In [69]:
from sklearn.feature_extraction.text import CountVectorizer

cnt_vect = CountVectorizer()
cnt_vect.fit(X_train)
X_train_cnt_vect = cnt_vect.transform(X_train)
X_test_cnt_vect = cnt_vect.transform(X_test)

print('학습 데이터 Text의 CountVectorizer Shape:', X_train_cnt_vect.shape)

학습 데이터 Text의 CountVectorizer Shape: (11314, 101631)

In [72]:
X_train_cnt_vect

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1103627 stored elements and shape (11314, 101631)>

In [71]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

lr_clf = LogisticRegression()
lr_clf.fit(X_train_cnt_vect , y_train)
pred = lr_clf.predict(X_test_cnt_vect)
print('예측 정확도는 {0:.3f}'.format(accuracy_score(y_test, pred)))

예측 정확도는 0.608

In [ ]:
y_test[0]

# 결과
# np.int64(4)
# 
# 4번 카테고리에 있는 'comp.sys.mac.hardware' 관련 내용이라는 뜻

np.int64(4)

In [77]:
print(X_test[0])

The tech support line for GCC is 1-800-231-1570.

In [ ]:
cnt_vect = CountVectorizer(min_df=10, max_df=0.85, stop_words='english')
cnt_vect.fit(X_train)
X_train_cnt_vect = cnt_vect.transform(X_train)
X_test_cnt_vect = cnt_vect.transform(X_test)

print('학습 데이터 Text의 CountVectorizer Shape:', X_train_cnt_vect.shape)

# 단어 10만개가 1만개로 줄어든것을 확인 할 수 있음

학습 데이터 Text의 CountVectorizer Shape: (11314, 10441)

In [73]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer()
tfidf_vect.fit(X_train)
X_train_tfidf_vect = tfidf_vect.transform(X_train)
X_test_tfidf_vect = tfidf_vect.transform(X_test)
lr_clf = LogisticRegression()
lr_clf.fit(X_train_tfidf_vect , y_train)
pred = lr_clf.predict(X_test_tfidf_vect)
print('예측 정확도는 {0:.3f}'.format(accuracy_score(y_test ,pred)))

예측 정확도는 0.674

In [ ]:
lr_clf = LogisticRegression()
lr_clf.fit(X_train_cnt_vect , y_train)
pred = lr_clf.predict(X_test_cnt_vect)
print('예측 정확도는 {0:.3f}'.format(accuracy_score(y_test, pred)))

# 0.608에서 0.613으로 정확도가 조금 더 증가한 것을 확인 할 수 있다.

예측 정확도는 0.613

In [80]:
cnt_vect = CountVectorizer(min_df=10, max_df=0.85, stop_words='english', ngram_range=(1, 2))
# ngram_range=(1, 2)추가

cnt_vect.fit(X_train)
X_train_cnt_vect = cnt_vect.transform(X_train)
X_test_cnt_vect = cnt_vect.transform(X_test)

print('학습 데이터 Text의 CountVectorizer Shape:', X_train_cnt_vect.shape)

학습 데이터 Text의 CountVectorizer Shape: (11314, 12721)

In [81]:
tfidf_vect = TfidfVectorizer(min_df=10, max_df=0.85, stop_words='english', ngram_range=(1, 2))

tfidf_vect.fit(X_train)
X_train_cnt_vect = tfidf_vect.transform(X_train)
X_test_cnt_vect = tfidf_vect.transform(X_test)

print('학습 데이터 Text의 CountVectorizer Shape:', X_train_tfidf_vect.shape)

학습 데이터 Text의 CountVectorizer Shape: (11314, 101631)

- #### 한글 텍스트 분석

In [82]:
pip install konlpy

Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl.metadata (1.9 kB)
Collecting JPype1>=0.7.0 (from konlpy)
  Downloading jpype1-1.7.1-cp314-cp314-win_amd64.whl.metadata (4.3 kB)
Collecting lxml>=4.1.0 (from konlpy)
  Downloading lxml-6.1.3-cp314-cp314-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: numpy>=1.6 in c:\Users\samsung1\git_project\samsung_practice\.venv\Lib\site-packages (from konlpy) (2.5.1)
Requirement already satisfied: packaging in c:\Users\samsung1\git_project\samsung_practice\.venv\Lib\site-packages (from JPype1>=0.7.0->konlpy) (26.2)
Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
   ---------------------------------------- 0.0/19.4 MB ? eta -:--:--
   ----- ---------------------------------- 2.6/19.4 MB 14.3 MB/s eta 0:00:02
   ----------------- ---------------------- 8.4/19.4 MB 21.9 MB/s eta 0:00:01
   ------------------------------ --------- 14.9/19.4 MB 25.2 MB/s eta 0:00:01
   ---------------------------------------- 19.4/19.4 MB 25.2 MB/s  0:00:00
Downloading jpype1-1.7.1-cp314-cp314-win_amd64.whl (364 kB)
Downloading lxml-6.1.3-cp314-cp314-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ---------------------------------------- 4.1/4.1 MB 27.8 MB/s  0:00:00
Installing collected packages: lxml, JPype1, konlpy

   ---------------------------------------- 0/3 [lxml]
   ------------- -------------------------- 1/3 [JPype1]
   ------------- -------------------------- 1/3 [JPype1]
   -------------------------- ------------- 2/3 [konlpy]
   ---------------------------------------- 3/3 [konlpy]

Successfully installed JPype1-1.7.1 konlpy-0.6.0 lxml-6.1.3
Note: you may need to restart the kernel to use updated packages.

In [1]:
import konlpy

In [2]:
with open('./data/소나기.txt', 'r', encoding='utf8') as f:
    text = f.read()
print(text[:200])

소년은 개울가에서 소녀를 보자 곧 윤 초시네 증손녀(曾孫女)딸이라는 걸 알 수
있었다. 소녀는 개울에다 손을 잠그고 물장난을 하고 있는 것이다. 서울서는 이런
개울물을 보지 못하기나 한 듯이.
벌써 며칠째 소녀는, 학교에서 돌아오는 길에 물장난이었다. 그런데, 어제까지 개울
기슭에서 하더니, 오늘은 징검다리 한가운데 앉아서 하고 있다.
소년은 개울둑에 앉아

In [3]:
import re

compile = re.compile("[^ ㄱ-ㅣ가-힣\\.]+")
text = compile.sub('',text)
print(text[:200])

소년은 개울가에서 소녀를 보자 곧 윤 초시네 증손녀딸이라는 걸 알 수있었다. 소녀는 개울에다 손을 잠그고 물장난을 하고 있는 것이다. 서울서는 이런개울물을 보지 못하기나 한 듯이.벌써 며칠째 소녀는 학교에서 돌아오는 길에 물장난이었다. 그런데 어제까지 개울기슭에서 하더니 오늘은 징검다리 한가운데 앉아서 하고 있다.소년은 개울둑에 앉아 버렸다. 소녀가 비키기

In [4]:
# 문장 토큰화
import nltk

sentences = nltk.sent_tokenize(text)
print(sentences[:3])

['소년은 개울가에서 소녀를 보자 곧 윤 초시네 증손녀딸이라는 걸 알 수있었다.', '소녀는 개울에다 손을 잠그고 물장난을 하고 있는 것이다.', '서울서는 이런개울물을 보지 못하기나 한 듯이.벌써 며칠째 소녀는 학교에서 돌아오는 길에 물장난이었다.']

In [5]:
# 단어 토큰화
from konlpy.tag import Okt
okt = Okt()
words = []
for sentence in sentences:
    word = okt.morphs(sentence)
    words.append(word)
print(words[:2])

[['소년', '은', '개울가에서', '소녀', '를', '보자', '곧', '윤', '초시', '네', '증손녀', '딸', '이라는', '걸', '알', '수', '있었다', '.'], ['소녀', '는', '개울', '에다', '손', '을', '잠그고', '물장난', '을', '하고', '있는', '것', '이다', '.']]

In [6]:
test_text = '나는 정말로 파이썬을 좋아한다. 아니 머신러닝을 더 좋아한다.'

print('normalize :', okt.normalize(test_text))
print('morphs :', okt.morphs(test_text))
print('nouns :', okt.nouns(test_text))
print('phrases :', okt.phrases(test_text))
print('pos :', okt.pos(test_text))

normalize : 나는 정말로 파이썬을 좋아한다. 아니 머신러닝을 더 좋아한다.
morphs : ['나', '는', '정말로', '파이썬', '을', '좋아한다', '.', '아니', '머신', '러닝', '을', '더', '좋아한다', '.']
nouns : ['나', '파이썬', '머신', '러닝', '더']
phrases : ['파이썬', '머신러닝', '머신', '러닝']
pos : [('나', 'Noun'), ('는', 'Josa'), ('정말로', 'Adverb'), ('파이썬', 'Noun'), ('을', 'Josa'), ('좋아한다', 'Adjective'), ('.', 'Punctuation'), ('아니', 'Adjective'), ('머신', 'Noun'), ('러닝', 'Noun'), ('을', 'Josa'), ('더', 'Noun'), ('좋아한다', 'Adjective'), ('.', 'Punctuation')]

In [7]:
okt = Okt()

def okt_tokenizer(text):
    tokens_ko = okt.morphs(text, stem=True)
    return tokens_ko
word_tokens = okt_tokenizer(text)
print(word_tokens[:20])

['소년', '은', '개다', '소녀', '를', '보다', '곧', '윤', '초시', '네', '증손녀', '딸', '이라는', '걸', '알', '수', '있다', '.', '소녀', '는']

In [8]:
with open('./data/stopword.txt','r',encoding='utf-8') as f:
    word = f.read()
stopwords = word.split('\n')
print(stopwords[:10])

['않다', '되어다', '되다', '하다', '어떻다', '이렇다', '이다', '어제', '매일', '아']

In [9]:
filtered_words = []
for word in word_tokens:
    if word not in stopwords:
        filtered_words.append(word)
print(filtered_words[:20])

['소년', '은', '개다', '소녀', '보다', '윤', '초시', '증손녀', '딸', '이라는', '걸', '알', '수', '.', '소녀', '는', '개울', '에다', '손', '잠그다']

In [10]:
def Stopwords(words, Stopwords = None):
    filtered_words = []
    for word in words:
        if word not in stopwords:
            filtered_words.append(word)
    return filtered_words
filtered_words = Stopwords(word_tokens, stopwords)
print(filtered_words[:20])

['소년', '은', '개다', '소녀', '보다', '윤', '초시', '증손녀', '딸', '이라는', '걸', '알', '수', '.', '소녀', '는', '개울', '에다', '손', '잠그다']

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

cnt_vect = CountVectorizer(tokenizer=okt_tokenizer, stop_words=stopwords)
cnt_vect.fit(filtered_words)
words_cnt_vect = cnt_vect.transform(filtered_words)
words_cnt_vect

c:\Users\samsung1\git_project\samsung_practice\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:527: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\samsung1\git_project\samsung_practice\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:412: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['\t', '가다', '각하', '간', '갖다', '개', '거나', '거리', '걸', '겁', '것과', '견지', '결과', '결론', '고려', '곤', '곳', '공동', '관', '관계', '관련', '구체', '구토', '그러하다', '그런', '그렇게', '그렇다', '그치다', '근거', '기대', '기점', '기준', '김', '까닭', '나머지', '남', '낫다', '낼', '년도', '논', '누가', '는', '다', '다르다', '다시', '달다', '답', '대로', '대하', '대해', '더', '더불다', '더욱이', '도', '도달', '도착', '동시', '됏', '두번째', '뒤', '뒤따르다', '든', '든지', '들다', '듯', '따다', '따르다', '따름', '때문', '라', '라도', '라면', '리하', '마자', '막론', '만', '만으로', '만은', '만이', '만큼', '만하', '많다', '말', '말다', '망정', '메', '면', '모르다', '몰랏다', '못', '무릎', '미치다', '바', '바꾸다', '밖에', '반대', '방면', '번째', '보다', '보아', '본대', '부류', '불구', '불문', '비', '비걱거리', '비교', '비기다', '비추다', '뿐', '사람', '상대', '생각', '서', '서술', '수', '시오', '시작', '시초', '쓰다', '쓰이다', '아니다', '아래', '아무', '아우르다', '안', '안다', '안되다', '알', '알다', '앞', '어기', '어떠하다', '어쨋', '어쩔', '어찌됏', '없다', '에도', '에야', '여보', '여전하다', '연', '연관', '옆', '오다', '외', '요', '요만', '우', '울다', '위', '위해', '윗', '은', '의거', '의지', '의치', '의하다', '이러하다', '이렇게', '이로', '이르다', '이서', '이외', '이용', '이유', '인', '인하다', '일반', '일지', '임', '입', '입다', '입장', '잇따르다', '적', '점', '정도', '제외', '젠', '종합', '좋다', '주저', '줄', '중', '즈음', '지', '지경', '지다', '진짜', '집', '쪽', '차', '차다', '첫', '총', '켜다', '크다', '토', '통', '틀림없다', '틈타다', '편이', '하고', '하든', '하자', '한', '한적', '함', '항목', '해', '해도', '해보다', '향', '허다', '형식', '후', '힘'] not in stop_words.
  warnings.warn(

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2308 stored elements and shape (2276, 834)>

In [12]:
from konlpy.tag import Hannanum

hannanum = Hannanum()

print(hannanum.analyze(u'롯데마트의 흑마늘 양념 치킨이 논란이 되고 있다.'))
print(hannanum.morphs(u'롯데마트의 흑마늘 양념 치킨이 논란이 되고 있다.'))
print(hannanum.nouns(u'다람쥐 헌 쳇바퀴에 타고파'))
print(hannanum.pos(u'웃으면 더 행복합니다!'))

[[[('롯데마트', 'ncn'), ('의', 'jcm')], [('롯데마트의', 'ncn')], [('롯데마트', 'nqq'), ('의', 'jcm')], [('롯데마트의', 'nqq')]], [[('흑마늘', 'ncn')], [('흑마늘', 'nqq')]], [[('양념', 'ncn')]], [[('치킨', 'ncn'), ('이', 'jcc')], [('치킨', 'ncn'), ('이', 'jcs')], [('치킨', 'ncn'), ('이', 'ncn')]], [[('논란', 'ncpa'), ('이', 'jcc')], [('논란', 'ncpa'), ('이', 'jcs')], [('논란', 'ncpa'), ('이', 'ncn')]], [[('되', 'nbu'), ('고', 'jcj')], [('되', 'nbu'), ('이', 'jp'), ('고', 'ecc')], [('되', 'nbu'), ('이', 'jp'), ('고', 'ecs')], [('되', 'nbu'), ('이', 'jp'), ('고', 'ecx')], [('되', 'paa'), ('고', 'ecc')], [('되', 'paa'), ('고', 'ecs')], [('되', 'paa'), ('고', 'ecx')], [('되', 'pvg'), ('고', 'ecc')], [('되', 'pvg'), ('고', 'ecs')], [('되', 'pvg'), ('고', 'ecx')], [('되', 'px'), ('고', 'ecc')], [('되', 'px'), ('고', 'ecs')], [('되', 'px'), ('고', 'ecx')]], [[('있', 'paa'), ('다', 'ef')], [('있', 'px'), ('다', 'ef')]], [[('.', 'sf')], [('.', 'sy')]]]
['롯데마트', '의', '흑마늘', '양념', '치킨', '이', '논란', '이', '되', '고', '있', '다', '.']
['다람쥐', '쳇바퀴', '타고파']
[('웃', 'P'), ('으면', 'E'), ('더', 'M'), ('행복', 'N'), ('하', 'X'), ('ㅂ니다', 'E'), ('!', 'S')]

In [ ]:
from konlpy.tag import Kkma

kkma = Kkma()

print(kkma.morphs(u'공부를 하면할수록 모르는게 많다는 것을 알게 됩니다.'))
print(kkma.nouns(u'대학에서 DB, 통계학, 이산수학 등을 배웠지만...'))
print(kkma.pos(u'다 까먹어버렸네요?ㅋㅋ'))
print(kkma.sentences(u'그래도 계속 공부합니다. 재밌으니까!'))

# Kkma는 너무 오래 걸려서 실제로 쓸때는 딴거 쓰셈

['공부', '를', '하', '면', '하', 'ㄹ수록', '모르', '는', '것', '이', '많', '다는', '것', '을', '알', '게', '되', 'ㅂ니다', '.']
['대학', '통계학', '이산', '이산수학', '수학', '등']
[('다', 'MAG'), ('까먹', 'VV'), ('어', 'ECD'), ('버리', 'VXV'), ('었', 'EPT'), ('네요', 'EFN'), ('?', 'SF'), ('ㅋㅋ', 'EMO')]
['그래도 계속 공부합니다.', '재밌으니까!']

In [14]:
from konlpy.tag import Komoran

komoran = Komoran()

print(komoran.morphs(u'우왕 코모란도 오픈소스가 되었어요'))
print(komoran.nouns(u'오픈소스에 관심 많은 멋진 개발자님들!'))
print(komoran.pos(u'혹시 바람과 함께 사라지다 봤어?'))

['우왕', '코', '모란', '도', '오픈', '소스', '가', '되', '었', '어요']
['오픈', '소스', '관심', '개발자']
[('혹시', 'MAG'), ('바람과 함께 사라지다', 'NNP'), ('보', 'VV'), ('았', 'EP'), ('어', 'EF'), ('?', 'SF')]

In [ ]:
# 얘는 따로 설치가 필요함
# from konlpy.tag import Mecab

# mecab = Mecab()

- #### 텍스트 분류 실습

In [15]:
import pandas as pd

df = pd.read_csv('./data/petition_sample_100.csv')
df.head()

,article_id,start,end,answered,votes,category,title,content
0,384828,2018-09-19,2018-10-19,0,30,외교/통일/국방,한국의 대통령 자격이 아닌 문재인 대통령,한국 대통령 자격으로 북한간게 맞는지 싶다. 북한환영 거리에 태극기는 찾아볼수 ...
1,58843,2017-12-05,2018-01-04,0,0,안전/환경,우리나라 시간을 되찾읍시다....,박정희! 다카키 마사오가 천한페하에게 갖다 바친 우리나라 시간을 찾자!! 조선시대에...
2,335145,2018-08-10,2018-09-09,0,3,일자리,노인복지정책에대하여,안녕하세요\n요즘사회적으로 문제가되는 고령사회 노인일자리에대한 기발한아이템이있어 청...
3,183881,2018-04-03,2018-05-03,0,17,미래,국회의원 고통분담해라 임금개혁해라,우리나라 국회의원들이 받는 세비는 연간 1억4000만 원. 이는 세계경제협력개발기구...
4,297960,2018-07-06,2018-08-05,0,4,외교/통일/국방,후방 부대의 실체,저는 부산 육군 보급부대에서 일햇던 병사입니다.\n저는 현재 의가사판정을 받고 제대...

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1700 entries, 0 to 1699
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   article_id  1700 non-null   int64
 1   start       1700 non-null   str
 2   end         1700 non-null   str
 3   answered    1700 non-null   int64
 4   votes       1700 non-null   int64
 5   category    1700 non-null   str
 6   title       1700 non-null   str
 7   content     1700 non-null   str
dtypes: int64(3), str(5)
memory usage: 106.4 KB

In [20]:
df['category'].value_counts()

category
외교/통일/국방       100
안전/환경          100
일자리            100
미래             100
기타             100
농산어촌           100
교통/건축/국토       100
보건복지           100
행정             100
육아/교육          100
정치개혁           100
저출산/고령화대책      100
인권/성평등         100
문화/예술/체육/언론    100
경제민주화          100
반려동물           100
성장동력           100
Name: count, dtype: int64

In [23]:
df['content'] = df['title'] + ' ' + df['content']

In [24]:
from sklearn.preprocessing import LabelEncoder

df_data = df[['content', 'category']]

lb_enc = LabelEncoder()
df_data['category'] = lb_enc.fit_transform(df_data['category'])
df_data.head()

                                             content  category
0  한국의 대통령  자격이 아닌 문재인 대통령 한국 대통령 자격으로  북한간게  맞는지...        10
1  우리나라 시간을 되찾읍시다.... 박정희! 다카키 마사오가 천한페하에게 갖다 바친 ...         9
2  노인복지정책에대하여 안녕하세요\n요즘사회적으로 문제가되는 고령사회 노인일자리에대한 ...        13
3  국회의원 고통분담해라 임금개혁해라 우리나라 국회의원들이 받는 세비는 연간 1억400...         5
4  후방 부대의 실체 저는 부산 육군 보급부대에서 일햇던 병사입니다.\n저는 현재 의가...        10

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test =train_test_split(df_data['content'], df_data['category'], test_size = 0.2, random_state = 0)
print(f'학습 데이터 수:{len(X_train)}, 평가 데이터 수:{len(X_test)}')

학습 데이터 수:1360, 평가 데이터 수:340

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

cnt_vect = CountVectorizer(tokenizer = okt_tokenizer)
cnt_vect.fit(X_train)
X_train_cnt_vect = cnt_vect.transform(X_train)
X_test_cnt_vect = cnt_vect.transform(X_test)

c:\Users\samsung1\git_project\samsung_practice\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:527: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr_clf = LogisticRegression()
lr_clf.fit(X_train_cnt_vect , y_train)
pred = lr_clf.predict(X_test_cnt_vect)
print('예측 정확도는 {0:.3f}'.format(accuracy_score(y_test,pred)))

예측 정확도는 0.338

c:\Users\samsung1\git_project\samsung_practice\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

- #### 감성분석
  - IMDB 영화 평가 분석

In [ ]:
import pandas as pd

review_df = pd.read_csv('./data/labeledTrainData.tsv', header=0, sep="\t", quoting=3)
review_df.head(3)

         id  sentiment                                             review
0  "5814_8"          1  "With all this stuff going down at the moment ...
1  "2381_9"          1  "\"The Classic War of the Worlds\" by Timothy ...
2  "7759_3"          0  "The film starts with a manager (Nicholas Bell...

In [ ]:
import re

review_df['review'] = review_df['review'].str.replace('<br />',' ')
review_df['review'] = review_df['review'].apply( lambda x : re.sub("[^a-zA-Z]", " ", x))
review_df.head(3)

         id  sentiment                                             review
0  "5814_8"          1   With all this stuff going down at the moment ...
1  "2381_9"          1     The Classic War of the Worlds   by Timothy ...
2  "7759_3"          0   The film starts with a manager  Nicholas Bell...

In [34]:
from sklearn.model_selection import train_test_split 

class_df = review_df['sentiment']
feature_df = review_df.drop(['id','sentiment'], axis=1)
X_train, X_test, y_train, y_test = train_test_split(feature_df, class_df, test_size=0.2, random_state=156)
print(X_train.shape, X_test.shape)

(20000, 1) (5000, 1)

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score

cnt_vect = CountVectorizer(stop_words='english', ngram_range=(1, 2))
cnt_vect.fit(X_train['review'])
X_train_cnt_vect = cnt_vect.transform(X_train['review'])
X_test_cnt_vect = cnt_vect.transform(X_test['review'])

In [41]:
lr_clf = LogisticRegression()
lr_clf.fit(X_train_cnt_vect, y_train)
pred = lr_clf.predict(X_test_cnt_vect)
pred_probs = lr_clf.predict_proba(X_test_cnt_vect)[:, 1]

print(f'예측 정확도는 {accuracy_score(y_test ,pred):.4f}')
print(f'ROC-AUC는 {roc_auc_score(y_test, pred_probs):.4f}')

예측 정확도는 0.8944
ROC-AUC는 0.9560

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer(stop_words='english', ngram_range=(1,2), min_df=10 )
tfidf_vect.fit(X_train['review'])
X_train_tfidf_vect = tfidf_vect.transform(X_train['review'])
X_test_tfidf_vect = tfidf_vect.transform(X_test['review'])

In [45]:
lr_clf = LogisticRegression()
lr_clf.fit(X_train_tfidf_vect, y_train)
pred = lr_clf.predict(X_test_tfidf_vect)
pred_probs = lr_clf.predict_proba(X_test_tfidf_vect)[:,1]

print(f'예측 정확도는 {accuracy_score(y_test, pred):.4f}')
print(f'ROC-AUC는 {roc_auc_score(y_test, pred_probs):.4f}')

예측 정확도는 0.8936
ROC-AUC는 0.9611

In [48]:
new_text = ['Talking to you makes my day.']

new_text_vect = tfidf_vect.transform(new_text)

result = lr_clf.predict(new_text_vect)

if result[0] == 1:
    print('긍정')
else:
    print('부정')

긍정

In [47]:
result

array([1])

In [49]:
df = pd.read_csv('data/네이버 영화 리뷰.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   content  1000 non-null   str
 1   score    1000 non-null   int64
dtypes: int64(1), str(1)
memory usage: 15.8 KB

In [50]:
df['score'].value_counts()

score
10    529
8      96
6      78
9      72
1      60
2      52
7      47
4      35
5      24
3       7
Name: count, dtype: int64

In [53]:
# 분류 > 10, 9 : 긍정(2)   /   6 ~ 8 : 중립(1)   /   5 이하 : 부정(0)

def score_convert(score):
    if score >= 9:
        return 2
    elif score >= 6:
        return 1
    else:
        return 0

y = df['score'].apply(score_convert)

print(y)

0      2
1      2
2      2
3      2
4      0
      ..
995    2
996    1
997    2
998    1
999    0
Name: score, Length: 1000, dtype: int64

In [59]:
def score_convert(score):
    if score >= 9:
        return 2
    elif score >= 6:
        return 1
    else:
        return 0

df['sentiment'] = df['score'].apply(score_convert)

print(y)

0      2
1      2
2      2
3      2
4      0
      ..
995    2
996    1
997    2
998    1
999    0
Name: score, Length: 1000, dtype: int64

In [65]:
# 컨텐츠에 비어있는 문자("''") -> 누락값을 제외하기
df['content'] = df['content'].apply(lambda text: None if text == "''" else text)
df_na = df.dropna()

In [66]:
y = df_na['sentiment']
X = df_na['content']

In [67]:
X.shape

(9,)

In [ ]:
import re

compile = re.compile("[^ ㄱ-ㅣ가-힣\\.]+")
text = compile.sub('',text)
print(text[:200])

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cnt_vect = CountVectorizer(tokenizer=okt_tokenizer)
X_cnt_vect = cnt_vect.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_cnt_vect, y, test_size=0.2, random_state=0)

NameError: name 'X_cnt_vect' is not defined

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)

print(accuracy_score(y_test, pred))

- #### 토픽 모델링
  - LDA(Latent Dirichlet Allocation)

In [69]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

cats = ['rec.motorcycles', 'rec.sport.baseball', 'comp.graphics',
        'comp.windows.x', 'talk.politics.mideast',
        'soc.religion.christian', 'sci.electronics', 'sci.med']

news_df= fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'), categories=cats, random_state=0)

In [ ]:
lda

- #### 유사도 분석
  - 코사인 유사도 실습

In [70]:
import numpy as np

def cos_similarity(v1, v2):
    dot_product = np.dot(v1, v2)
    l2_norm = (np.sqrt(sum(np.square(v1))) * np.sqrt(sum(np.square(v2))))
    similarity = dot_product / l2_norm

    return similarity

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

doc_list = ['if you take the blue pill, the story ends',
            'if you take the red pill, you stay in Wonderland',
            'if you take the red pill, I show you how deep the rabbit hole goes']

tfidf_vect_simple = TfidfVectorizer()
feature_vect_simple = tfidf_vect_simple.fit_transform(doc_list)
print(feature_vect_simple.shape)

(3, 18)

In [ ]:
feature_vect_array = feature_vect_simple.toarray()

vect1 = np.array(feature_vect_array[0]).reshape(-1, )
vect2 = np.array(feature_vect_array[1]).reshape(-1, )

similarity_simple = cos_similarity(vect1, vect2)
print('문장1, 문장2 코사인유사도: {0:.3f}'.format(similarity_simple))

문장1, 문장2 코사인유사도: 0.402

In [75]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_simple_pair = cosine_similarity(feature_vect_simple, feature_vect_simple)

print(similarity_simple_pair)
print('shape:',similarity_simple_pair.shape)

[[1.         0.40207758 0.40425045]
 [0.40207758 1.         0.45647296]
 [0.40425045 0.45647296 1.        ]]
shape: (3, 3)