### Step 1. 필요한 라이브러리 임포트

In [4]:
import pandas as pd

### Step 2. [데이터](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) 확인

- order_id 주문번호
- quantity 주문 개수
- item_name 주문한 상품명
- choice_description 선택사항
- item_price 가격

### Step 3. 데이터 불러오기


**read_csv를 통해 데이터를 올바른 형태로 불러온 뒤 chipo에 저장해주세요**  
data: chipotle.tsv

In [ ]:
chipo = pd.read_csv('data/chipotle.tsv', sep = '\t')
chipo.head()

#order_id = 1이 4개가 있는걸 보아 메뉴를 4개 주문한 것을 확인할 수 있다.

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [15]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

### Step 4. 누락값 확인하기
chipo에서 누락값이 존재하는지 확인해주세요

In [10]:
chipo.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

### Step 5. item_price에서 $를 없애고 float 형식으로 새롭게 저장해주세요.

In [ ]:
chipo['item_price']     # $가 숫자 맨 앞에 표시된 것을 확인할 수 있음

0        $2.39
1        $3.39
2        $3.39
3        $2.39
4       $16.98
         ...
4617    $11.75
4618    $11.75
4619    $11.25
4620     $8.75
4621     $8.75
Name: item_price, Length: 4622, dtype: str

In [18]:
def price(x):               # 맨 앞의 달러 기호를 제거하는 함수
    return float(x[1:]) 

chipo['item_price'] = chipo['item_price'].apply(price)    
# 내가 만든 함수 적용 및 원래 테이블에 변경사항 적용(저장)

### Step 6. 아이템별 주문 수를 출력해주세요

In [21]:
# ~별 이런문제는 groupby라고 보면 됨
# 즉 아이템 이름끼리 묶어라는 의미

chipo.groupby('item_name')['order_id'].count()

# order_id에 누락값이 없는걸 알기 때문에 count() 사용

item_name
6 Pack Soft Drink                         54
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            162
Bowl                                       2
Burrito                                    6
Canned Soda                              104
Canned Soft Drink                        301
Carnitas Bowl                             68
Carnitas Burrito                          59
Carnitas Crispy Tacos                      7
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             726
Chicken Burrito                          553
Chicken Crispy Tacos                      47
Chicken Salad                              9
Chicken Salad Bowl                       110
Chicken Soft Tacos                       115
Chips                                    211
Chips and Fresh Tomato Salsa             110
Chips and Guacamole                      479
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        22
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     43
Chips and Tomatillo Red Chili Salsa       48
Chips and Tomatillo-Green Chili Salsa     31
Chips and Tomatillo-Red Chili Salsa       20
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          27
Salad                                      2
Side of Chips                            101
Steak Bowl                               211
Steak Burrito                            368
Steak Crispy Tacos                        35
Steak Salad                                4
Steak Salad Bowl                          29
Steak Soft Tacos                          55
Veggie Bowl                               85
Veggie Burrito                            95
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          7
Name: order_id, dtype: int64

### Step 7. 아이템별 주문 총량을 출력해주세요.

In [22]:
chipo.groupby('item_name')['quantity'].sum()

item_name
6 Pack Soft Drink                         55
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            211
Bowl                                       4
Burrito                                    6
Canned Soda                              126
Canned Soft Drink                        351
Carnitas Bowl                             71
Carnitas Burrito                          60
Carnitas Crispy Tacos                      8
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             761
Chicken Burrito                          591
Chicken Crispy Tacos                      50
Chicken Salad                              9
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Chips                                    230
Chips and Fresh Tomato Salsa             130
Chips and Guacamole                      506
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        23
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     45
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo-Green Chili Salsa     33
Chips and Tomatillo-Red Chili Salsa       25
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          29
Salad                                      2
Side of Chips                            110
Steak Bowl                               221
Steak Burrito                            386
Steak Crispy Tacos                        36
Steak Salad                                4
Steak Salad Bowl                          31
Steak Soft Tacos                          56
Veggie Bowl                               87
Veggie Burrito                            97
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          8
Name: quantity, dtype: int64

### Step 8. 각 아이템의 가격을 구해서 unit_price 컬럼에 추가해주세요.
주문당 quantity가 1일때의 가격 (item_price / quantity)

In [26]:
chipo['unit_price'] = chipo['item_price'] / chipo['quantity']
chipo.head()

,order_id,quantity,item_name,choice_description,item_price,unit_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49

### Step 9. 아이템별 개당 가격의 평균을 구하고 가장 비싼순으로 5개를 출력해주세요

In [28]:
result = chipo.groupby('item_name')['unit_price'].mean()
result

item_name
6 Pack Soft Drink                         6.490000
Barbacoa Bowl                            10.187273
Barbacoa Burrito                          9.832418
Barbacoa Crispy Tacos                    10.087273
Barbacoa Salad Bowl                      10.640000
Barbacoa Soft Tacos                      10.018400
Bottled Water                             1.431667
Bowl                                      7.400000
Burrito                                   7.400000
Canned Soda                               1.090000
Canned Soft Drink                         1.250000
Carnitas Bowl                            10.315588
Carnitas Burrito                          9.975932
Carnitas Crispy Tacos                     9.852857
Carnitas Salad                            8.990000
Carnitas Salad Bowl                      11.056667
Carnitas Soft Tacos                       9.398500
Chicken Bowl                              9.657727
Chicken Burrito                           9.475949
Chicken Crispy Tacos                      9.492340
Chicken Salad                             9.010000
Chicken Salad Bowl                        9.909091
Chicken Soft Tacos                        9.240261
Chips                                     2.149242
Chips and Fresh Tomato Salsa              2.748727
Chips and Guacamole                       4.345616
Chips and Mild Fresh Tomato Salsa         3.000000
Chips and Roasted Chili Corn Salsa        2.950000
Chips and Roasted Chili-Corn Salsa        2.390000
Chips and Tomatillo Green Chili Salsa     2.950000
Chips and Tomatillo Red Chili Salsa       2.950000
Chips and Tomatillo-Green Chili Salsa     2.390000
Chips and Tomatillo-Red Chili Salsa       2.390000
Crispy Tacos                              7.400000
Izze                                      3.390000
Nantucket Nectar                          3.390000
Salad                                     7.400000
Side of Chips                             1.690000
Steak Bowl                               10.232559
Steak Burrito                             9.993424
Steak Crispy Tacos                        9.952857
Steak Salad                               8.915000
Steak Salad Bowl                         11.027931
Steak Soft Tacos                          9.578182
Veggie Bowl                              10.011882
Veggie Burrito                            9.602842
Veggie Crispy Tacos                       8.490000
Veggie Salad                              8.490000
Veggie Salad Bowl                        10.138889
Veggie Soft Tacos                         9.352857
Name: unit_price, dtype: float64

In [30]:
result.sort_values(ascending = False).head()

item_name
Carnitas Salad Bowl    11.056667
Steak Salad Bowl       11.027931
Barbacoa Salad Bowl    10.640000
Carnitas Bowl          10.315588
Steak Bowl             10.232559
Name: unit_price, dtype: float64

In [ ]:
chipo.groupby('item_name')['unit_price'].mean().sort_values(ascending = False).head()
# 한줄로 쓸 수도 있긴 한데 굳이 싶

item_name
Carnitas Salad Bowl    11.056667
Steak Salad Bowl       11.027931
Barbacoa Salad Bowl    10.640000
Carnitas Bowl          10.315588
Steak Bowl             10.232559
Name: unit_price, dtype: float64

### Step 10. 한 주문(같은 order_id)에 20달러 이상 지불한 손님을 출력해주세요.

In [41]:
chipo_price = chipo.groupby('order_id')['item_price'].sum()

chipo_price[chipo_price >= 20]

order_id
4       21.00
18      24.90
20      36.20
21      23.36
26      20.50
        ...
1827    32.95
1829    24.25
1830    23.00
1833    23.50
1834    28.75
Name: item_price, Length: 589, dtype: float64

In [44]:
chipo_price_index = chipo_price[chipo_price >= 20].index
    # 조건에 맞는 데이터의 인덱스만 뽑아올 수 있다.
chipo_price_index

Index([   4,   18,   20,   21,   26,   28,   30,   34,   40,   43,
       ...
       1811, 1812, 1822, 1824, 1825, 1827, 1829, 1830, 1833, 1834],
      dtype='int64', name='order_id', length=589)

### Step 11. 위 10번에서 주문량이 2개인 아이템중 가장 많이 팔린 아이템은 무엇인가요?
Chips and Guacamole

In [45]:
# chipo_price_index -> 총 주문 금액이 20달러 이상인 주문 번호
chipo['order_id'].isin(chipo_price_index)

0       False
1       False
2       False
3       False
4       False
        ...
4617     True
4618     True
4619     True
4620     True
4621     True
Name: order_id, Length: 4622, dtype: bool

In [47]:
chipo2 = chipo[chipo['order_id'].isin(chipo_price_index)]
chipo2

,order_id,quantity,item_name,choice_description,item_price,unit_price
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
35,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, Rice]",8.75,8.75
36,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75,8.75
37,18,1,Chips and Guacamole,NaN,4.45,4.45
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

In [49]:
chipo2[chipo2['quantity'] == 2]['item_name'].value_counts()

item_name
Chips and Guacamole                      20
Chicken Bowl                             17
Canned Soft Drink                        15
Chicken Burrito                          13
Chips                                    12
Steak Burrito                            11
Chicken Salad Bowl                       10
Canned Soda                               7
Bottled Water                             6
Steak Bowl                                6
Chicken Crispy Tacos                      3
Chicken Soft Tacos                        3
Chips and Tomatillo Green Chili Salsa     2
Steak Salad Bowl                          2
Nantucket Nectar                          2
Chips and Tomatillo Red Chili Salsa       2
Chips and Fresh Tomato Salsa              2
Carnitas Bowl                             1
Chips and Tomatillo-Red Chili Salsa       1
Steak Crispy Tacos                        1
6 Pack Soft Drink                         1
Veggie Bowl                               1
Chips and Tomatillo-Green Chili Salsa     1
Veggie Soft Tacos                         1
Carnitas Crispy Tacos                     1
Steak Soft Tacos                          1
Name: count, dtype: int64

### Step 12. Veggie Salad Bowl은 몇 건 주문되었나요?

In [51]:
chipo[chipo['item_name'] == 'Veggie Salad Bowl'].shape[0]

18

### Step 13. Chicken이 포함된 음식은 몇 가지가 있나요?

In [ ]:
import re

def check_chicken(x):       # Chicken이라는 단어를 검색하는 함수를 만듬
    return bool(re.search('Chicken', x))    # Chicken단어가 있으면 True

In [ ]:
chipo['item_name'].apply(check_chicken)

0       False
1       False
2       False
3       False
4        True
        ...
4617    False
4618    False
4619     True
4620     True
4621     True
Name: item_name, Length: 4622, dtype: bool

In [ ]:
chipo[chipo['item_name'].apply(check_chicken)]['item_name'].unique()

# chicken이라는 단어가 들어간 메뉴 종류가 6가지임을 확인할 수 있다.

<StringArray>
[        'Chicken Bowl', 'Chicken Crispy Tacos',   'Chicken Soft Tacos',
      'Chicken Burrito',   'Chicken Salad Bowl',        'Chicken Salad']
Length: 6, dtype: str

In [ ]:
chipo['item_name'].str.contains('Chicken')
# 정규표현식을 쓰지 않고도 Chicken 단어가 있는 데이터를 찾을 수 있다.

0       False
1       False
2       False
3       False
4        True
        ...
4617    False
4618    False
4619     True
4620     True
4621     True
Name: item_name, Length: 4622, dtype: bool

In [ ]:
chipo[chipo['item_name'].str.contains('Chicken')]['item_name'].unique()

<StringArray>
[        'Chicken Bowl', 'Chicken Crispy Tacos',   'Chicken Soft Tacos',
      'Chicken Burrito',   'Chicken Salad Bowl',        'Chicken Salad']
Length: 6, dtype: str